%YAML 1.2
---
Logger:
  Level: DEBUG
  LogDirectory: ${WEBAI_HOME}/logs/
  LogName: rtai
  PipeToStdout: True
  UseCalleeStack: True
  TranscriptLogName: transcript
StoryEngine:
  UseGui: False # Changing this is not reccomended
  WorkerThreadTimerMs: 1000
  AgentTimerSec: 5
  NarrationTimerSec: 12
  # DebugTimerSec: 30
  # StopAfterCycles: 5 # Exits the program after X cycles
  StopAfterDays: 1 # Exits the program after X days
  WorldClockScaleMs: 500 # Minutes to milliseconds
Narrator:
Agents:
  NumAgents: 1
LLMClient: # This is the client that connects to the LLM
  model_name: "mistral"
  base_url: "http://192.168.1.70:1234/v1"
  api_key: "not-needed"
...