%YAML 1.2
---
Logger:
  Level: DEBUG
  LogDirectory: ${WEBAI_HOME}/logs/
  LogName: rtai
  PipeToStdout: True
  UseCalleeStack: True
  TranscriptLogName: transcript
StoryEngine:
  UseGui: False # Not implemented
  WorkerThreadTimerMs: 1000
  AgentTimerMillis: 5
  NarrationTimerSec: 12
  # DebugTimerSec: 30
  # StopAfterCycles: 5 # Exits the program after X cycles
  # StopAfterDays: 2 # Exits the program after X days
Narrator:
Agents:
  NumAgents: 2
World:
  Clock:
    StartDate: '2024-01-01'
    StartTime: '06:15:00 AM'
    ClockIncrementSec: 30 # Amount that clock is incremented by each cycle
    ClockTimerMillis: 500 # Amount of time between clock increments
LLMClient: # This is the client that connects to the LLM
  use_server: False
  local_model_path: "/Users/nyeung/Projects/llama.cpp/models/mistral-7b-instruct-v0.2.Q4_K_M.gguf"
  model_name: "mistral-7b-instruct-v0.2.Q4_K_M.gguf"
  base_url: "http://localhost:1234/v1" # for llm server
  api_key: "not-needed"
...